### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by RJVB09** [HyperFunOriginal/LudiPhys#1]
- Better mouse controls (invert or something)
- Make a more accesible save and load menu
- Use GPU (for the future)
- Post processing (shaders?)
- New sim button on main menu
- List of keybinds in-game?

**Comment by HyperFunOriginal** [comment]
Gonna try to do as well as I can

**Comment by HyperFunOriginal** [comment]
Done:
- Better mouse controls
- New Sim button

**Comment by HyperFunOriginal** [comment]
- Added post-processing
I think we're going to end with this for now.
